version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ../:/app
    environment:
      - MONGO_URI=mongodb://mongo:27017/recruitment_db
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=password
      - DB_NAME=recruitment_db
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - AWS_REGION=${AWS_REGION}
      - S3_BUCKET=${S3_BUCKET}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - HF_API_TOKEN=${HF_API_TOKEN}
    depends_on:
      mongo:
        condition: service_healthy
      ollama:
        condition: service_started
    ports:
      - "5000:5000"
    networks:
      - recruitment-net

  mongo:
    image: mongo:6.0
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.runCommand('ping').ok"]
      interval: 10s
      retries: 5
    networks:
      - recruitment-net

  ollama:
    image: ollama/ollama
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - recruitment-net

volumes:
  mongo_data:
  ollama_data:

networks:
  recruitment-net:
    driver: bridge
